export enum EClassStatus {
  CANCELED = 'CANCELED',
  SCHEDULED = 'SCHEDULED',
  FULL = 'FULL',
  POSTPONED = 'POSTPONED',
  COMPLETED = 'COMPLETED',
  IN_PROGRESS = 'IN_PROGRESS',
  OPEN_FOR_ENROLLMENT = 'OPEN_FOR_ENROLLMENT'
}
